name: task_management_system

description: TaskHub — Ứng dụng di động Quản lý Công việc cho Doanh nghiệp.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  # Geofence / chấm công bằng GPS
  geolocator: ^13.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/

